stages:
  - plan_terraform
  - apply_terraform

.plan_terraform: &plan_terraform
  stage: plan_terraform
  script:
    - cd ${TF_ENVIRONMENT}
    - terraform init -no-color
    - terraform plan -no-color -out=tfplan

  artifacts:
    untracked: true
    expire_in: 1 day
    paths:
      - ${TF_ENVIRONMENT}/.terraform/**/*
      - ${TF_ENVIRONMENT}/tfplan

plan_terraform_dev:
  image: docker.dev.slicelife.com/gitlab-runner-terraform-12:stable
  <<: *plan_terraform
  variables:
    IAM_ROLE: $IAM_ROLE_TERRAFORM_DEV
    TF_ENVIRONMENT: development
    VAULT_ADDR: $VAULT_ADDR_DEV
    VAULT_TOKEN: $VAULT_TOKEN_DEV
  tags:
    - development

plan_terraform_prod:
  image: docker.prod.slicelife.com/gitlab-runner-terraform-12:stable
  <<: *plan_terraform
  variables:
    IAM_ROLE: $IAM_ROLE_TERRAFORM_PROD
    TF_ENVIRONMENT: production
    VAULT_ADDR: $VAULT_ADDR_PROD
    VAULT_TOKEN: $VAULT_TOKEN_PROD
  tags:
    - production
  only:
    - master

.apply_terraform: &apply_terraform
  stage: apply_terraform
  script:
    - cd ${TF_ENVIRONMENT}
    - terraform apply -no-color tfplan

  artifacts:
    paths:
      - ${TF_ENVIRONMENT}/.terraform

apply_terraform_dev:
  <<: *apply_terraform
  image: docker.dev.slicelife.com/gitlab-runner-terraform-12:stable
  variables:
    IAM_ROLE: $IAM_ROLE_TERRAFORM_DEV
    TF_ENVIRONMENT: development
    VAULT_ADDR: $VAULT_ADDR_DEV
    VAULT_TOKEN: $VAULT_TOKEN_DEV
  tags:
    - development
#  only:
#    - master
  when: manual
  allow_failure: false

apply_terraform_prod:
  <<: *apply_terraform
  image: docker.prod.slicelife.com/gitlab-runner-terraform-12:stable
  variables:
    IAM_ROLE: $IAM_ROLE_TERRAFORM_PROD
    TF_ENVIRONMENT: production
    VAULT_ADDR: $VAULT_ADDR_PROD
    VAULT_TOKEN: $VAULT_TOKEN_PROD
  tags:
    - production
  only:
    - master
  when: manual
  allow_failure: false
